Restaurant.UI/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Restaurant.UI.ViewModels
{
    public class LoginViewModel
    {
        [EmailAddress]
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [DataType(DataType.Password)]
        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

Restaurant.UI/Controllers/AccessController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Domain.DTO;
using Domain.Enum;
using Domain.InterfaceServices;
using Microsoft.Owin.Security;
using Restaurant.BLL.Services;
using Restaurant.UI.ViewModels;

namespace Restaurant.UI.Controllers
{
    public class AccessController : Controller
    {
        private readonly IUserService _userService;

        private IAuthenticationManager AuthenticationManager => HttpContext.GetOwinContext().Authentication;

        public AccessController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            await SetInitialDataAsync();
            if (ModelState.IsValid)
            {
                UserDTO userDto = new UserDTO { Email = model.Email, Password = model.Password };
                ClaimsIdentity claim = await _userService.Authenticate(userDto);
                if (claim == null)
                {
                    ModelState.AddModelError("", @"Wrong login or password.");
                }
                else
                {
                    AuthenticationManager.SignOut();
                    AuthenticationManager.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = false
                    }, claim);

                    return RedirectToAction("ShowAllOrders", "Order");
                }
            }
            return View(model);
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("ShowAllOrders", "Order");
        }

        private async Task SetInitialDataAsync()
        {
            await _userService.SetInitialData(new UserDTO
            {
                Email    = "admin@mail.ru",
                UserName = "admin@mail.ru",
                Password = "12qw!@QW",
                Name     = "Admin",
                Role     = (int)RoleEnum.admin
            }, new List<string> { "waiter", "admin", "cook" });
        }
    }
}

Restaurant.UI/Views/Access/Login.cshtml
@model Restaurant.UI.ViewModels.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2 class="title" style="text-align: left">@ViewBag.Title</h2>

@using (Html.BeginForm("Login","Access",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2 text-info" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2 text-info" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btncustom"/>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}